file_format: "1"
id: cholibri
name: Cholibri
type: shield
url: https://github.com/
requires: [pro_micro]
features:
  - keys
  - pointer
exposes:
  - i2c_glidepoint
siblings:
  - cholibri_left
  - cholibri_right
